### ISSUE TITLE
Cannot find module './shim'

### ISSUE THREAD

**Issue by piwnk** [odoe/jsapi-webpack#2]
Running on Win10.

**Comment by piwnk** [comment]
Full error message:
Error: Cannot find module './shim'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (#\jsapi-webpack\node_modules\util.promisify\index.js:9:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (#\jsapi-webpack\node_modules\html-webpack-plugin\index.js:4:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by booshwa** [comment]
Had the same problem, got it working with `npm install @dojo/shim`.  https://github.com/dojo/shim
